{
    "openapi": "3.1.0",
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "paths": {
        "/": {
            "get": {
                "summary": "Home Endpoint",
                "description": "A simple endpoint that indicates the server is running.\nNo parameters are required. Returns a message indicating the server status.",
                "operationId": "home__get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HomeResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "summary": "Health Check Endpoint",
                "operationId": "health_check_health_get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HealthStatus"
                                },
                                "example": {
                                    "status": "Healthy"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Error Response",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "model_uninitialized": {
                                        "summary": "Model not initialized",
                                        "value": {
                                            "detail": "Model not initialized"
                                        }
                                    },
                                    "pipeline_uninitialized": {
                                        "summary": "Pipeline not initialized",
                                        "value": {
                                            "detail": "Pipeline not initialized"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/completions": {
            "post": {
                "summary": "Chat Endpoint",
                "description": "Processes chat requests, generating text based on the specified text-generation pipeline.",
                "operationId": "generate_text_v1_completions_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UnifiedRequestModel"
                            },
                            "examples": {
                                "text_generation_example": {
                                    "summary": "Text Generation Example",
                                    "description": "An example of a text generation request.",
                                    "value": {
                                        "prompt": "Tell me a joke",
                                        "return_full_text": true,
                                        "clean_up_tokenization_spaces": false,
                                        "temperature": 1
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "text_generation": {
                                        "summary": "Text Generation Response",
                                        "value": {
                                            "Result": "Generated text based on the prompt."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "examples": {
                                    "missing_prompt": {
                                        "summary": "Missing Prompt",
                                        "value": {
                                            "detail": "Text generation parameter prompt required"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/metrics": {
            "get": {
                "summary": "Metrics Endpoint",
                "description": "Provides system metrics, including GPU details if available, or CPU and memory usage otherwise.\nUseful for monitoring the resource utilization of the server running the ML models.",
                "operationId": "get_metrics_v1_metrics_get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/MetricsResponse"
                                },
                                "examples": {
                                    "gpu_metrics": {
                                        "summary": "Example when GPUs are available",
                                        "value": {
                                            "gpu_info": [
                                                {
                                                    "id": "GPU-1234",
                                                    "name": "GeForce GTX 950",
                                                    "load": "25.00%",
                                                    "temperature": "55 C",
                                                    "memory": {
                                                        "used": "1.00 GB",
                                                        "total": "2.00 GB"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    "cpu_metrics": {
                                        "summary": "Example when only CPU is available",
                                        "value": {
                                            "cpu_info": {
                                                "load_percentage": 20,
                                                "physical_cores": 4,
                                                "total_cores": 8,
                                                "memory": {
                                                    "used": "4.00 GB",
                                                    "total": "16.00 GB"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "CPUInfo": {
                "properties": {
                    "load_percentage": {
                        "type": "number",
                        "title": "Load Percentage"
                    },
                    "physical_cores": {
                        "type": "integer",
                        "title": "Physical Cores"
                    },
                    "total_cores": {
                        "type": "integer",
                        "title": "Total Cores"
                    },
                    "memory": {
                        "$ref": "#/components/schemas/MemoryInfo"
                    }
                },
                "type": "object",
                "required": [
                    "load_percentage",
                    "physical_cores",
                    "total_cores",
                    "memory"
                ],
                "title": "CPUInfo"
            },
            "ErrorResponse": {
                "properties": {
                    "detail": {
                        "type": "string",
                        "title": "Detail"
                    }
                },
                "type": "object",
                "required": [
                    "detail"
                ],
                "title": "ErrorResponse"
            },
            "GPUInfo": {
                "properties": {
                    "id": {
                        "type": "string",
                        "title": "Id"
                    },
                    "name": {
                        "type": "string",
                        "title": "Name"
                    },
                    "load": {
                        "type": "string",
                        "title": "Load"
                    },
                    "temperature": {
                        "type": "string",
                        "title": "Temperature"
                    },
                    "memory": {
                        "$ref": "#/components/schemas/MemoryInfo"
                    }
                },
                "type": "object",
                "required": [
                    "id",
                    "name",
                    "load",
                    "temperature",
                    "memory"
                ],
                "title": "GPUInfo"
            },
            "HTTPValidationError": {
                "properties": {
                    "detail": {
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        },
                        "type": "array",
                        "title": "Detail"
                    }
                },
                "type": "object",
                "title": "HTTPValidationError"
            },
            "HealthStatus": {
                "properties": {
                    "status": {
                        "type": "string",
                        "title": "Status",
                        "example": "Healthy"
                    }
                },
                "type": "object",
                "required": [
                    "status"
                ],
                "title": "HealthStatus"
            },
            "HomeResponse": {
                "properties": {
                    "message": {
                        "type": "string",
                        "title": "Message",
                        "example": "Server is running"
                    }
                },
                "type": "object",
                "required": [
                    "message"
                ],
                "title": "HomeResponse"
            },
            "MemoryInfo": {
                "properties": {
                    "used": {
                        "type": "string",
                        "title": "Used"
                    },
                    "total": {
                        "type": "string",
                        "title": "Total"
                    }
                },
                "type": "object",
                "required": [
                    "used",
                    "total"
                ],
                "title": "MemoryInfo"
            },
            "MetricsResponse": {
                "properties": {
                    "gpu_info": {
                        "anyOf": [
                            {
                                "items": {
                                    "$ref": "#/components/schemas/GPUInfo"
                                },
                                "type": "array"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Gpu Info"
                    },
                    "cpu_info": {
                        "anyOf": [
                            {
                                "$ref": "#/components/schemas/CPUInfo"
                            },
                            {
                                "type": "null"
                            }
                        ]
                    }
                },
                "type": "object",
                "title": "MetricsResponse"
            },
            "UnifiedRequestModel": {
                "properties": {
                    "prompt": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Prompt",
                        "description": "Prompt for text generation. Required for text-generation pipeline."
                    },
                    "return_full_text": {
                        "anyOf": [
                            {
                                "type": "boolean"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Return Full Text",
                        "description": "Return full text if True, else only added text",
                        "default": true
                    },
                    "clean_up_tokenization_spaces": {
                        "anyOf": [
                            {
                                "type": "boolean"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Clean Up Tokenization Spaces",
                        "description": "Clean up extra spaces in text output",
                        "default": false
                    },
                    "prefix": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Prefix",
                        "description": "Prefix added to prompt"
                    },
                    "handle_long_generation": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Handle Long Generation",
                        "description": "Strategy to handle long generation"
                    },
                    "max_length": {
                        "type": "integer",
                        "title": "Max Length",
                        "default": 200
                    },
                    "min_length": {
                        "type": "integer",
                        "title": "Min Length",
                        "default": 0
                    },
                    "do_sample": {
                        "type": "boolean",
                        "title": "Do Sample",
                        "default": true
                    },
                    "num_beams": {
                        "type": "integer",
                        "title": "Num Beams",
                        "default": 1
                    },
                    "temperature": {
                        "type": "number",
                        "title": "Temperature",
                        "default": 1
                    },
                    "top_k": {
                        "type": "integer",
                        "title": "Top K",
                        "default": 10
                    },
                    "top_p": {
                        "type": "number",
                        "title": "Top P",
                        "default": 1
                    }
                },
                "additionalProperties": true,
                "type": "object",
                "title": "UnifiedRequestModel",
                "example": {
                    "additional_param": "Example value",
                    "clean_up_tokenization_spaces": false,
                    "max_length": 200,
                    "prompt": "Tell me a joke",
                    "return_full_text": true,
                    "temperature": 0.7,
                    "top_p": 0.9
                }
            },
            "ValidationError": {
                "properties": {
                    "loc": {
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "type": "array",
                        "title": "Location"
                    },
                    "msg": {
                        "type": "string",
                        "title": "Message"
                    },
                    "type": {
                        "type": "string",
                        "title": "Error Type"
                    }
                },
                "type": "object",
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "title": "ValidationError"
            }
        }
    }
}